cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<slug:category_slug>/', views.all_products, name='products_by_category'),
    path('<product_id>', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254, unique=True)
    slug = models.SlugField(max_length=254, unique=True)
    
    def get_url(self):
        return reverse('products_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=254, unique=True)
    slug = models.SlugField(max_length=254, unique=True)
    description = models.TextField()
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                 blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(
            variation_category='color', is_active=True
            )

    def sizes(self):
        return super(VariationManager, self).filter(
            variation_category='size', is_active=True
            )


variation_choice = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

products/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from .models import Product, Category
from cart.models import CartItem, Cart
from cart.views import _cart_id
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def all_products(request, category_slug=None):
    """ A view to show all products, including sorting and search queries """

    categories = None
    products = None
    query = None
    sort = None
    direction = None

    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')  # Display only available products
        
    # Search and sort products
    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               ("You didn't enter any search criteria!"))
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query) | Q(slug__icontains=query) 
            products = products.filter(queries)
            
    current_sorting = f'{sort}_{direction}'
    
    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details"""
    try:
        product = get_object_or_404(Product, pk=product_id)

        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(request), product=product
            ).exists()
    except Exception as e:
        raise e

    context = {
        'product': product,
        'in_cart': in_cart,
    }

    return render(request, 'products/product_detail.html', context)

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if product.image %}
                    <a href="{{ product.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid" src="/media/noimage.png" alt="{{ product.name }}">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">&euro; {{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if product.rating %}
                    <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 10</small>
                    {% else %}
                    <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <small class="ml-3">
                        <a href="#">Edit</a> |
                        <a class="text-danger" href="#">Delete</a>
                    </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% if product.category.name == 'Clothes' %}
                            <hr class="w-100">
                            <div class="mt-2 pt-3 col-12">
                                <div class="item-option-select ">
                                    <h6>Product Color:</h6>
                                    <select name="color" class="form-control" required>
                                        <option value="" disabled selected>Chose Color</option>
                                        {% for i in product.variation_set.colors %}
                                            <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="mt-2 pt-3 col-12 mb-3">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-control">
                                        <option value="" disabled selected>Chose Size</option>
                                        {% for i in product.variation_set.sizes %}
                                            <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <hr class="w-100 mt-5">
                            {% endif %}
                            <div class="col-12 mt-2">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                {% if product.stock <= 0 %}
                                    <a href="{% url 'add_to_cart' product.id %}" class="btn btn-danger rounded-0 mt-5"
                                        style="pointer-events: none;"> <span class="text"><s>Add to
                                                cart</s></span> <i class="fas fa-shopping-cart"></i> </a>
                                    <h6 class="text-danger text-right mt-1 text-uppercase">Out of stock</h6>
                                {% else %}
                                    <button type="submit" class="btn btn-black rounded-0 mt-5"> <span
                                        class="text">Add to
                                        cart</span> <i class="fas fa-shopping-cart"></i> </button>
                                {% endif %}
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">`
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-9">
                <div>
                    <h3>Customer Reviews </h3>
                </div>
                <div class="box mb-3">
                    <div class="icontext w-100">
                        <img src="#" class="img-xs icon rounded-circle">
                        <div class="text">
                            <span class="date text-muted float-md-right">24.04.2020 </span>
                            <h6 class="mb-1">Mike John </h6>
                        </div>
                    </div>
                    <div class="mt-3">
                        <p>
                            Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}